# Generated by Django 3.0.4 on 2020-03-30 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must enter in this format', regex='^(\\+98|0)?9\\d{9}$')])),
                ('otp', models.CharField(blank=True, max_length=4)),
                ('count', models.PositiveIntegerField(default=0)),
                ('verify', models.BooleanField(default=False)),
            ],
        ),
    ]
